### ISSUE TITLE
Error in if (zero_range(range)) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by IsmailM** [SBCS-Bioinformatics/R-Core#103]
Affects 14 Geo datasets

```
Running: Rscript '/data/home/bt11112/R-Core/overview.R' --dbrdata /data/home/bt11112/analysis/GDS1095/GDS1095.RData --rundir '/data/home/bt11112/analysis/GDS1095/overview/' --analyse 'Boxplot,PCA' --accession GDS1095 --factor 'cell.type' --popA 'Lin negative, CD34 negative' --popB 'Lin negative, CD34 positive,Lin positive, CD34 positive' --popname1 'Group1' --popname2 'Group2' --dev TRUE


[1] "Overview: GeoDiver is starting"
[1] "Overview: Libraries have been loaded"
[1] "Overview: Data Preprocessed!"
[1] "Overview: Factors and Populations have been set"
Error in if (zero_range(range)) { : missing value where TRUE/FALSE needed
Calls: samples.boxplot ... <Anonymous> -> f -> train_cartesian -> expand_range
Execution halted

```

[zero_range_error.txt](https://github.com/SBCS-Bioinformatics/R-Core/files/154460/zero_range_error.txt)

**Comment by sureshhewabi** [comment]
Three Issues found:

1. Population names contain commas
2. Population names contain apostrophe
3. Very bad dataset containing plenty of missing values.

Solutions:

1.  needs to be validated from UI
2.  needs to be validated from UI
3. KNN Imputation was implemented to fill missing values.

Detailed description is available for each case in the attachment
[Debug Results.docx](https://github.com/SBCS-Bioinformatics/R-Core/files/164075/Debug.Results.docx)

**Comment by IsmailM** [comment]
I don't think you can simply remove the comma from the Population names - as the dataset will still have it and as such will still fail...

**Comment by sureshhewabi** [comment]
It works if you we give exact population name given in the dataset. 
`Ex: --popB 'Ku86 knockout, Terc wildtype,Ku86 knockout, Terc knockout,Ku86 wildtype, Terc knockout'`
this will not work. In R, if I hard code it as 
`population2     <- c("Ku86 knockout, Terc wildtype","Ku86 knockout, Terc knockout","Ku86 wildtype, Terc knockout")`

Currently we separate factor by comma. We might need to change some logic in that case. Let me think what we can do.

**Comment by sureshhewabi** [comment]
Sorry for creating an Issue to change from front end.

**Comment by sureshhewabi** [comment]
I think we can separate list by $ sign. is it possible to check all the populations of all the dataset and figure out whether they have used $ sign for population names?

**Comment by IsmailM** [comment]
I don’t think that’s a long term solution - you never know if someone decides tomorrow to have the $ in the population name… Also we still have the issue of the `’` in the population name…

Let me have a look at the code tomorrow…

**Comment by IsmailM** [comment]
So I think I have a fix:

Use the below `split_arg(argv$pop)` function instead of `unlist(strsplit(argv$pop, ",”))`

```R
split_arg <- function(vector_arg) {
  pos <- unlist(gregexpr("[^\\\\],", vector_arg, perl=TRUE))
  vect <- substring(vector_arg, c(1, pos+2), c(pos, nchar(vector_arg))) # expected result
  vect <- gsub("\\\\,", ",", vect) # replace \\, with ,
  vect <- gsub("\\\"", '"', vect) #replace \" with "
  return (vect)
}
```

Then simply escape any `,` within a population/factor name i.e.

```bash

--popB "Ku86 knockout\, Terc wildtype,Ku86 knockout\, Terc knockout,Ku86 wildtype\, Terc knockout"

```

**Comment by IsmailM** [comment]
I’ll deploy the fix shortly...

**Comment by sureshhewabi** [comment]
Yes please. Great to hear you got the solution

**Comment by IsmailM** [comment]
Should be fixed now
