### ISSUE TITLE
Repeated Colours in Heatmap

### ISSUE THREAD

**Issue by IsmailM** [SBCS-Bioinformatics/R-Core#81]
when individuals (patients) are selected colours repeat on heatmap and extends beyond height

SBCS-Bioinformatics/GEODiver#18

**Comment by sureshhewabi** [comment]
Fixed. If there is a factor having more that 10 factor levels, it will not show on the heatmap.
```
 # If there are only few factor levels, then only show colour annotations
  if(length(levels(exp[, "factor.type"])) < 10){
      ann.col$Factor <- exp[, "factor.type"]
      colnames(ann.col) <- c("Population", factor.type)
  }
  
```
